function psQuote(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function buildPowerShellInstallScript(
  endpoint: string,
  contentDefaultOn: boolean,
): string {
  const fallbackCollect = contentDefaultOn ? "1" : "0";
  return [
    "$ErrorActionPreference = 'Stop'",
    "$ProgressPreference = 'SilentlyContinue'",
    `$endpoint = if ($env:TOARD_INGEST_ENDPOINT) { $env:TOARD_INGEST_ENDPOINT } else { ${psQuote(endpoint)} }`,
    "$token = $env:TOARD_INGEST_TOKEN",
    "$contentSince = $env:TOARD_SHIM_COLLECT_CONTENT_SINCE",
    `if (-not $env:TOARD_SHIM_COLLECT_CONTENT) { $env:TOARD_SHIM_COLLECT_CONTENT = '${fallbackCollect}' }`,
    "if (-not $env:TOARD_SHIM_COLLECT_TOOLS) { $env:TOARD_SHIM_COLLECT_TOOLS = '1' }",
    "if (-not $token) { throw 'toard token is missing. Copy the install command again.' }",
    "$asset = 'toard-shim-x86_64-pc-windows-msvc.exe'",
    "$release = if ($env:TOARD_SHIM_RELEASE_BASE) { $env:TOARD_SHIM_RELEASE_BASE.TrimEnd('/') } else { 'https://github.com/devy1540/toard/releases/latest/download' }",
    "$temp = Join-Path ([IO.Path]::GetTempPath()) ('toard-' + [guid]::NewGuid())",
    "$userHome = if ($env:USERPROFILE) { $env:USERPROFILE } else { $HOME }",
    "$toardDir = Join-Path $userHome '.toard'",
    "$binDir = Join-Path $toardDir 'bin'",
    "$shim = Join-Path $binDir 'toard-shim.exe'",
    "$download = Join-Path $temp $asset",
    "$sums = Join-Path $temp 'SHA256SUMS'",
    "$hadEndpoint = Test-Path Env:TOARD_INGEST_ENDPOINT",
    "$savedEndpoint = $env:TOARD_INGEST_ENDPOINT",
    "$hadToken = Test-Path Env:TOARD_INGEST_TOKEN",
    "$savedToken = $env:TOARD_INGEST_TOKEN",
    "function Restore-ToardEnv([string]$Name, [bool]$HadValue, [string]$Value) {",
    "  if ($HadValue) { [Environment]::SetEnvironmentVariable($Name, $Value, 'Process') }",
    "  else { Remove-Item (\"Env:\" + $Name) -ErrorAction SilentlyContinue }",
    "}",
    "function Set-ToardPrivateAcl([string]$Path) {",
    "  $item = Get-Item -Force -LiteralPath $Path",
    "  $identity = [Security.Principal.WindowsIdentity]::GetCurrent().User",
    "  if ($item.PSIsContainer) {",
    "    $acl = New-Object System.Security.AccessControl.DirectorySecurity",
    "    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule($identity, 'FullControl', 'ContainerInherit,ObjectInherit', 'None', 'Allow')",
    "  } else {",
    "    $acl = New-Object System.Security.AccessControl.FileSecurity",
    "    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule($identity, 'FullControl', 'Allow')",
    "  }",
    "  $acl.SetOwner($identity)",
    "  $acl.SetAccessRuleProtection($true, $false)",
    "  [void]$acl.AddAccessRule($rule)",
    "  Set-Acl -LiteralPath $Path -AclObject $acl",
    "}",
    "New-Item -ItemType Directory -Force -Path $temp | Out-Null",
    "try {",
    '  Invoke-WebRequest -UseBasicParsing -Uri "$release/$asset" -OutFile $download',
    '  Invoke-WebRequest -UseBasicParsing -Uri "$release/SHA256SUMS" -OutFile $sums',
    "  $sumText = [IO.File]::ReadAllText($sums)",
    "  $match = [regex]::Match($sumText, '(?im)^([a-f0-9]{64})\\s+\\*?toard-shim-x86_64-pc-windows-msvc\\.exe\\s*$')",
    "  if (-not $match.Success) { throw 'checksum entry missing' }",
    "  $expected = $match.Groups[1].Value.ToLowerInvariant()",
    "  $actual = (Get-FileHash -Algorithm SHA256 -Path $download).Hash.ToLowerInvariant()",
    "  if ($actual -ne $expected) { throw 'checksum mismatch' }",
    "  New-Item -ItemType Directory -Force -Path $binDir | Out-Null",
    "  foreach ($name in @('claude.exe', 'codex.exe', 'toard-shim.exe')) {",
    "    Copy-Item -Force $download (Join-Path $binDir $name)",
    "  }",
    "",
    "  $capability = @(& $shim @('capabilities'))",
    "  $capabilityExit = $LASTEXITCODE",
    "  if ($capabilityExit -ne 0 -or $capability.Count -ne 1 -or $capability[0] -ne 'multi-target-v1') {",
    "    throw 'installed toard-shim does not support multi-target-v1'",
    "  }",
    "",
    "  try {",
    "    $env:TOARD_INGEST_ENDPOINT = $endpoint",
    "    $env:TOARD_INGEST_TOKEN = $token",
    "    if ($contentSince) { $env:TOARD_SHIM_COLLECT_CONTENT_SINCE = $contentSince }",
    "    else { Remove-Item Env:TOARD_SHIM_COLLECT_CONTENT_SINCE -ErrorAction SilentlyContinue }",
    "    & $shim @('target', 'upsert')",
    "    $upsertExit = $LASTEXITCODE",
    "  } finally {",
    "    Restore-ToardEnv 'TOARD_INGEST_ENDPOINT' $hadEndpoint $savedEndpoint",
    "    Restore-ToardEnv 'TOARD_INGEST_TOKEN' $hadToken $savedToken",
    "  }",
    "  if ($upsertExit -ne 0) { throw 'toard target registration failed.' }",
    "",
    "  Get-ChildItem -Force -Recurse $toardDir | ForEach-Object { Set-ToardPrivateAcl $_.FullName }",
    "  Set-ToardPrivateAcl $toardDir",
    "",
    "  $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')",
    "  $parts = @($userPath -split ';' | Where-Object { $_ })",
    "  $hasUserPath = $parts | Where-Object { $_.TrimEnd('\\') -ieq $binDir.TrimEnd('\\') }",
    "  if (-not $hasUserPath) {",
    "    [Environment]::SetEnvironmentVariable('Path', ($binDir + ';' + ($parts -join ';')).TrimEnd(';'), 'User')",
    "  }",
    "  $hasProcessPath = ($env:Path -split ';') | Where-Object { $_.TrimEnd('\\') -ieq $binDir.TrimEnd('\\') }",
    "  if (-not $hasProcessPath) { $env:Path = $binDir + ';' + $env:Path }",
    "",
    "  & $shim @('daemon', 'install')",
    "  $daemonExit = $LASTEXITCODE",
    "  if ($daemonExit -ne 0) { throw 'toard periodic collection registration failed.' }",
    "",
    "  try {",
    "    $env:TOARD_INGEST_ENDPOINT = $endpoint",
    "    Remove-Item Env:TOARD_INGEST_TOKEN -ErrorAction SilentlyContinue",
    "    & $shim @('doctor', '--target-env')",
    "    $doctorExit = $LASTEXITCODE",
    "  } finally {",
    "    Restore-ToardEnv 'TOARD_INGEST_ENDPOINT' $hadEndpoint $savedEndpoint",
    "    Restore-ToardEnv 'TOARD_INGEST_TOKEN' $hadToken $savedToken",
    "  }",
    "  if ($doctorExit -ne 0) { throw 'toard doctor failed. Review the diagnostics above.' }",
    "  Write-Host 'toard 연결 완료'",
    "} finally {",
    "  Remove-Item -Recurse -Force -ErrorAction SilentlyContinue $temp",
    "}",
    "",
  ].join("\r\n");
}

export function buildPowerShellUninstallScript(endpoint: string): string {
  return [
    "$ErrorActionPreference = 'Stop'",
    `$endpoint = if ($env:TOARD_INGEST_ENDPOINT) { $env:TOARD_INGEST_ENDPOINT } else { ${psQuote(endpoint)} }`,
    "$userHome = if ($env:USERPROFILE) { $env:USERPROFILE } else { $HOME }",
    "$toardDir = Join-Path $userHome '.toard'",
    "$binDir = Join-Path $toardDir 'bin'",
    "$shim = Join-Path $binDir 'toard-shim.exe'",
    "$pendingFile = Join-Path $toardDir 'cleanup-pending'",
    "$hadEndpoint = Test-Path Env:TOARD_INGEST_ENDPOINT",
    "$savedEndpoint = $env:TOARD_INGEST_ENDPOINT",
    "Write-Host \"Warning: unsent local state for $endpoint may be removed.\"",
    "if (Test-Path $shim) {",
    "  try {",
    "    $env:TOARD_INGEST_ENDPOINT = $endpoint",
    "    $removeOutput = @(& $shim @('target', 'remove', '--machine'))",
    "    $removeExit = $LASTEXITCODE",
    "  } finally {",
    "    if ($hadEndpoint) { $env:TOARD_INGEST_ENDPOINT = $savedEndpoint }",
    "    else { Remove-Item Env:TOARD_INGEST_ENDPOINT -ErrorAction SilentlyContinue }",
    "  }",
    "} elseif ((Test-Path $pendingFile) -and ([IO.File]::ReadAllText($pendingFile).Trim().TrimEnd('/') -ieq $endpoint.TrimEnd('/'))) {",
    "  $removeOutput = @('removed=1', 'remaining=0')",
    "  $removeExit = 0",
    "} else { throw 'installed toard-shim or this server cleanup receipt was not found; target was not removed.' }",
    "if ($removeExit -ne 0) { throw 'toard target removal failed.' }",
    "if ($removeOutput.Count -ne 2) { throw 'invalid target remove machine output' }",
    "if ($removeOutput[0] -notmatch '^removed=([01])$') { throw 'invalid target remove machine output' }",
    "$removed = [int]$Matches[1]",
    "if ($removeOutput[1] -notmatch '^remaining=(\\d+)$') { throw 'invalid target remove machine output' }",
    "$remaining = [int]$Matches[1]",
    "if ($removed -eq 0) { Write-Host 'Target was not registered; no files changed.'; return }",
    "if ($remaining -gt 0) { Write-Host \"Target removed; $remaining target(s) remain, shim and daemon kept.\"; return }",
    "",
    "if (Test-Path $shim) {",
    "  & $shim @('daemon', 'uninstall')",
    "  $daemonExit = $LASTEXITCODE",
    "  if ($daemonExit -ne 0) { throw 'toard periodic collection removal failed.' }",
    "  & $shim @('claude-env', 'off') 2>$null",
    "}",
    "",
    "$codexConfig = Join-Path $userHome '.codex\\config.toml'",
    "if (Test-Path $codexConfig) {",
    "  $content = [IO.File]::ReadAllText($codexConfig)",
    "  $updated = [regex]::Replace($content, '(?ms)^# >>> toard otel >>>\\r?\\n.*?^# <<< toard otel <<<\\r?\\n?', '')",
    "  if ($updated -ne $content) {",
    "    Copy-Item -Force $codexConfig ($codexConfig + '.toard-bak')",
    "    [IO.File]::WriteAllText($codexConfig, $updated, (New-Object System.Text.UTF8Encoding($false)))",
    "  }",
    "}",
    "$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')",
    "$userParts = @($userPath -split ';' | Where-Object { $_ -and $_.TrimEnd('\\') -ine $binDir.TrimEnd('\\') })",
    "[Environment]::SetEnvironmentVariable('Path', ($userParts -join ';'), 'User')",
    "$processParts = @($env:Path -split ';' | Where-Object { $_ -and $_.TrimEnd('\\') -ine $binDir.TrimEnd('\\') })",
    "$env:Path = $processParts -join ';'",
    "foreach ($name in @('claude.exe', 'codex.exe', 'claude.exe.old', 'codex.exe.old', 'toard-shim.exe.old')) {",
    "  $path = Join-Path $binDir $name",
    "  if (Test-Path $path) { Remove-Item -Force $path }",
    "}",
    "foreach ($name in @('targets', 'legacy-backup', 'state')) {",
    "  $path = Join-Path $toardDir $name",
    "  if (Test-Path $path) { Remove-Item -Recurse -Force $path }",
    "}",
    "foreach ($name in @('credentials', 'registry.lock')) {",
    "  $path = Join-Path $toardDir $name",
    "  if (Test-Path $path) { Remove-Item -Force $path }",
    "}",
    "if (Test-Path $shim) { Remove-Item -Force $shim }",
    "if (Test-Path $pendingFile) { Remove-Item -Force $pendingFile }",
    "foreach ($dir in @($binDir, $toardDir)) {",
    "  if ((Test-Path $dir) -and -not (Get-ChildItem -Force $dir | Select-Object -First 1)) { Remove-Item -Force $dir }",
    "}",
    "Write-Host 'Last target and toard shim removed.'",
    "",
  ].join("\r\n");
}
