function shQuote(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

export function installScript(endpoint: string, contentDefaultOn: boolean): string {
  const collectDefault = contentDefaultOn ? "1" : "";
  return [
    "#!/bin/sh",
    "# toard shim 원클릭 설치. 사용:",
    "#   curl -fsSL <toard>/install.sh | TOARD_INGEST_TOKEN=tk_... sh",
    "set -eu",
    `DEFAULT_ENDPOINT=${shQuote(endpoint)}`,
    'ENDPOINT="${TOARD_INGEST_ENDPOINT:-$DEFAULT_ENDPOINT}"',
    'TOKEN="${TOARD_INGEST_TOKEN:-}"',
    'COLLECT="${TOARD_SHIM_COLLECT_CONTENT:-' + collectDefault + '}"',
    'COLLECT_TOOLS="${TOARD_SHIM_COLLECT_TOOLS:-1}"',
    'COLLECT_SINCE="${TOARD_SHIM_COLLECT_CONTENT_SINCE:-}"',
    'BIN_DIR="${TOARD_BIN_DIR:-$HOME/.toard/bin}"',
    'RELEASE_BASE="${TOARD_SHIM_RELEASE_BASE:-https://github.com/devy1540/toard/releases/latest/download}"',
    'SHIM="$BIN_DIR/toard-shim"',
    "",
    'if [ -z "$TOKEN" ]; then',
    '  echo "toard-shim: TOARD_INGEST_TOKEN 이 필요합니다. 설치 명령을 다시 복사하세요." >&2',
    "  exit 2",
    "fi",
    "",
    "# 1) checksum 검증 설치. target 등록 전 daemon이 뜨지 않도록 release installer는 항상 끈다.",
    'curl -fsSL "${RELEASE_BASE%/}/install.sh" | TOARD_INSTALL_DAEMON=0 sh',
    '[ -x "$SHIM" ] || { echo "toard-shim: 설치된 관리 바이너리를 찾을 수 없습니다" >&2; exit 1; }',
    "",
    "# 2) 새 registry를 지원하는 바이너리인지 먼저 확인한다. 실패 시 credentials는 건드리지 않는다.",
    'CAPABILITIES=$("$SHIM" capabilities 2>/dev/null || true)',
    'if [ "$CAPABILITIES" != "multi-target-v1" ]; then',
    '  echo "toard-shim: 설치된 바이너리가 multi-target-v1을 지원하지 않습니다" >&2',
    "  exit 1",
    "fi",
    "",
    "# 3) 이 서버 target만 추가·갱신한다. token은 환경변수이며 명령 인자나 스크립트 파일에 쓰지 않는다.",
    'TOARD_INGEST_ENDPOINT="$ENDPOINT" TOARD_INGEST_TOKEN="$TOKEN" TOARD_SHIM_COLLECT_CONTENT="$COLLECT" TOARD_SHIM_COLLECT_TOOLS="$COLLECT_TOOLS" TOARD_SHIM_COLLECT_CONTENT_SINCE="$COLLECT_SINCE" "$SHIM" target upsert',
    "",
    "# 4) 기존 Cursor user-global hook을 보존하면서 정확 토큰 stop hook을 등록한다.",
    '"$SHIM" cursor-hook install',
    "",
    "# 5) target 등록 후에만 주기 수집을 등록한다.",
    'case "${TOARD_INSTALL_DAEMON:-1}" in',
    '  1) "$SHIM" daemon install ;;',
    '  0) echo "주기 수집 데몬 건너뜀 — 나중에: toard-shim daemon install" ;;',
    '  *) echo "toard-shim: TOARD_INSTALL_DAEMON은 0 또는 1이어야 합니다" >&2; exit 2 ;;',
    "esac",
    "",
    "# 6) capability 확인 이후에만 PATH 설정을 변경한다.",
    'case ":$PATH:" in',
    '  *":$BIN_DIR:"*) ;;',
    "  *)",
    '    for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do',
    '      [ -f "$rc" ] || continue',
    "      grep -q 'toard/bin' \"$rc\" 2>/dev/null && continue",
    "      printf '\\nexport PATH=\"%s:$PATH\"  # toard shim\\n' \"$BIN_DIR\" >> \"$rc\"",
    "    done",
    '    echo "PATH 에 $BIN_DIR 추가됨(새 셸부터 적용)."',
    "    ;;",
    "esac",
    "",
    "# 7) 다른 target의 접속 상태와 무관하게 방금 등록한 endpoint만 진단한다.",
    'PATH="$BIN_DIR:$PATH" TOARD_INGEST_ENDPOINT="$ENDPOINT" "$SHIM" doctor --target-env',
    'echo "toard 연결 완료 — endpoint=$ENDPOINT"',
    "",
  ].join("\n");
}
