function shQuote(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

export function uninstallScript(endpoint: string): string {
  return [
    "#!/bin/sh",
    "# 이 스크립트를 제공한 toard 서버 target만 제거한다.",
    "set -eu",
    `DEFAULT_ENDPOINT=${shQuote(endpoint)}`,
    'ENDPOINT="${TOARD_INGEST_ENDPOINT:-$DEFAULT_ENDPOINT}"',
    'TOARD_DIR="$HOME/.toard"',
    'BIN_DIR="${TOARD_BIN_DIR:-$TOARD_DIR/bin}"',
    'SHIM="$BIN_DIR/toard-shim"',
    'PENDING_FILE="$TOARD_DIR/cleanup-pending"',
    "",
    'echo "경고: $ENDPOINT target의 미전송 로컬 상태가 함께 삭제될 수 있습니다."',
    'if [ -x "$SHIM" ]; then',
    '  RESULT=$(TOARD_INGEST_ENDPOINT="$ENDPOINT" "$SHIM" target remove --machine)',
    'elif [ -f "$PENDING_FILE" ] && { [ "$(cat "$PENDING_FILE")" = "$ENDPOINT" ] || [ "$(cat "$PENDING_FILE")" = "${ENDPOINT%/}" ]; }; then',
    "  RESULT='removed=1\nremaining=0'",
    "else",
    '  echo "toard-shim: 설치된 관리 바이너리나 이 서버의 정리 receipt를 찾을 수 없어 target을 제거하지 않았습니다" >&2',
    "  exit 1",
    "fi",
    'LINE_COUNT=$(printf "%s\\n" "$RESULT" | awk \'END { print NR }\')',
    'REMOVED=$(printf "%s\\n" "$RESULT" | sed -n \'1s/^removed=//p\')',
    'REMAINING=$(printf "%s\\n" "$RESULT" | sed -n \'2s/^remaining=//p\')',
    'if [ "$LINE_COUNT" -ne 2 ]; then',
    '  echo "toard-shim: target remove machine 출력이 올바르지 않습니다" >&2',
    "  exit 1",
    "fi",
    'case "$REMOVED" in 0|1) ;; *) echo "toard-shim: target remove machine 출력이 올바르지 않습니다" >&2; exit 1 ;; esac',
    'case "$REMAINING" in \'\'|*[!0-9]*) echo "toard-shim: target remove machine 출력이 올바르지 않습니다" >&2; exit 1 ;; esac',
    "",
    'if [ "$REMOVED" = "0" ]; then',
    '  echo "등록된 target이 없어 변경하지 않았습니다: $ENDPOINT"',
    "  exit 0",
    "fi",
    'if [ "$REMAINING" -gt 0 ]; then',
    '  echo "target 제거 완료: $ENDPOINT (남은 target=$REMAINING, shim·daemon 유지)"',
    "  exit 0",
    "fi",
    "",
    "# 실제 마지막 target을 제거한 경우에만 shim 전역 설치를 정리한다.",
    'if [ -x "$SHIM" ]; then',
    '  "$SHIM" daemon uninstall',
    '  "$SHIM" cursor-hook uninstall',
    '  { "$SHIM" claude-env off; } || true',
    "fi",
    "",
    "# codex의 과거 experimental OTLP 관리 블록만 제거한다.",
    'CFG="$HOME/.codex/config.toml"',
    "if [ -f \"$CFG\" ] && grep -q 'toard otel' \"$CFG\" 2>/dev/null; then",
    '  cp "$CFG" "$CFG.toard-bak"',
    "  awk '/# >>> toard otel >>>/{s=1} s==0{print} /# <<< toard otel <<</{s=0}' \"$CFG.toard-bak\" > \"$CFG\"",
    "fi",
    "",
    "# toard marker가 있는 PATH 행만 백업 후 제거한다.",
    'for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.profile"; do',
    '  [ -f "$rc" ] || continue',
    "  grep -q 'toard shim' \"$rc\" 2>/dev/null || continue",
    '  cp "$rc" "$rc.toard-bak"',
    "  grep -v 'toard shim' \"$rc.toard-bak\" > \"$rc\" || true",
    "done",
    "",
    "# receipt와 shim은 다른 정리가 끝난 뒤 제거해 중단 시 같은 uninstall을 재시도할 수 있게 한다.",
    'rm -f "$BIN_DIR/claude" "$BIN_DIR/codex" "$BIN_DIR/claude.old" "$BIN_DIR/codex.old" "$BIN_DIR/toard-shim.old"',
    'rm -rf "$TOARD_DIR/targets" "$TOARD_DIR/legacy-backup" "$TOARD_DIR/state" "$TOARD_DIR/cursor"',
    'rm -f "$TOARD_DIR/credentials" "$TOARD_DIR/registry.lock"',
    'rm -f "$BIN_DIR/toard-shim"',
    'rm -f "$PENDING_FILE"',
    'rmdir "$BIN_DIR" 2>/dev/null || true',
    'rmdir "$TOARD_DIR" 2>/dev/null || true',
    'echo "마지막 target과 toard shim 제거 완료. 실제 Claude/Codex와 원본 세션 로그는 유지됩니다."',
    "",
  ].join("\n");
}
